### ISSUE TITLE
content-type error

### ISSUE THREAD

**Issue by rajankouzina** [lingwooc/restpdf-magento2#1]
"message": "Content-Type header is invalid."

**Comment by lingwooc** [comment]
I have just tried this in 2.3.7 with eadesignro/module-pdfgenerator set up and verified working. This generates and encodes the pdf to a json output successfully. I should note that you need to patch eadesignro/module-pdfgenerator for it to work as its been abandoned. You might well be hitting related issues. 

These composer patches fix it.
```
            "eadesignro/module-pdfgenerator": {
                "Pull: https://github.com/EaDesgin/magento2-pdf-generator2/pull/101": "https://patch-diff.githubusercontent.com/raw/EaDesgin/magento2-pdf-generator2/pull/101.patch",
                "Pull: https://patch-diff.githubusercontent.com/raw/lingwooc/magento2-pdf-generator2/pull/1": "https://patch-diff.githubusercontent.com/raw/lingwooc/magento2-pdf-generator2/pull/1.patch"
            },
```

Apologies for the hilariously late response, as you have no doubt you've moved on.
