### ISSUE TITLE
Class Mpdf does not exist message show in body response.

### ISSUE THREAD

**Issue by Gagan557** [lingwooc/restpdf-magento2#2]
I added module in magento 2.3.I want to print pdf of invoice using rest api.
Url: http://localhost/jaipurdesign/rest/V1/invoices/1/pdf/1
Method: get
show error message 
"message": "Class Mpdf\\Mpdf does not exist",
    "code": -1,
    "trace": "#0 C:\\wamp64\\www\\jaipurdesign\\vendor\\magento\\framework\\Code\\Reader\\ClassReader.php(26): ReflectionClass->__construct('Mpdf\\\\Mpdf')\n#1 C:\\wamp64\\www\\jdrnew\\vendor\\magento\\framework\\ObjectManager\\Definition\\Runtime.php(54):
Please help how to resolve this issue.

**Comment by lingwooc** [comment]
That's odd. That module should be installed with eadesignro/module-pdfgenerator. Is the eadrsignro module working propperly?

I need to update this for 2.3 (and 2.4 for that matter) so it's not impossible that it is just broken at the moment.

**Comment by lingwooc** [comment]
I have just tried this in 2.3.7 with eadesignro/module-pdfgenerator set up and verified working. This generates and encodes the pdf to a json output successfully. I should note that you need to patch eadesignro/module-pdfgenerator for it to work as its been abandoned. You might well be hitting related issues. 

These composer patches fix it.
```
            "eadesignro/module-pdfgenerator": {
                "Pull: https://github.com/EaDesgin/magento2-pdf-generator2/pull/101": "https://patch-diff.githubusercontent.com/raw/EaDesgin/magento2-pdf-generator2/pull/101.patch",
                "Pull: https://patch-diff.githubusercontent.com/raw/lingwooc/magento2-pdf-generator2/pull/1": "https://patch-diff.githubusercontent.com/raw/lingwooc/magento2-pdf-generator2/pull/1.patch"
            },
```

Apologies for the hilariously late response, as you have no doubt you've moved on.
